---
# Source: https://metallb.universe.tf/tutorial/arp/
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: pi-jeef-me
      protocol: layer2
      addresses:
      # 14 available addresses
      - 192.168.2.240/28
