---
all:
  children:
    pis:
      hosts:
        raspi1.pi.jeef.me:
          mac: b8:27:eb:db:7f:5b
        raspi2.pi.jeef.me:
          mac: b8:27:eb:fe:1a:be
        raspi3.pi.jeef.me:
          mac: b8:27:eb:60:ae:e4
    zeros:
      hosts:
        zero1.pi.jeef.me:
          mac: b8:27:eb:35:fb:a1
        zero2.pi.jeef.me:
          mac: b8:27:eb:35:fb:a2
        zero3.pi.jeef.me:
          mac: b8:27:eb:35:fb:a3
        zero4.pi.jeef.me:
          mac: b8:27:eb:35:fb:a4
        zero5.pi.jeef.me:
          mac: b8:27:eb:35:fb:a5
