---
# https://github.com/carlosedp/kubernetes-arm/blob/master/2-Traefik/traefik-internal-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    debug = false
    logLevel = "INFO"

    # Do not verify backend certificates (use https backends)
    insecureSkipVerify = true
    enablePassTLSCert = true
    passHostHeader = true

    [kubernetes]

    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
      [entrypoints.metrics]
      address = ":8081"

    # dashboard
    [api]
    dashboard = true

    # https://<domain>/ping
    [ping]
    entryPoint = "http"

    [metrics]
      [metrics.prometheus]
      entryPoint = "metrics"

    # Let's Encrypt SSL certs
    [acme]
      email = "traefik@jeef.me"
      storage = "/data/acme.json"
      entryPoint = "https"
      onHostRule = true
      acmeLogging = true
        [[acme.domains]]
        main = "*.jeef.me"
        # sans = ["*.jeef.me"]
        # [acme.httpChallenge]
        # entryPoint = "http"
      [acme.dnsChallenge]
      provider = "digitalocean"
      delayBeforeCheck = 30
