---
- hosts: all

  tasks:

  - name: use /etc/docker/daemon.json to disable iptables
    copy:
      content: |
        {
          "iptables": false
        }
      dest: /etc/docker/daemon.json

  - systemd:
      daemon_reload: yes
      name: docker
      state: restarted
