apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: octobox
  name: octobox
  labels:
    app: octobox
spec:
  selector:
    matchLabels:
      app: octobox
  template:
    metadata:
      labels:
        app: octobox
    spec:
      containers:
      # https://github.com/jeefberkey/octobox/blob/docker-arm/docker_build.sh
      # you have to rebuild the container, because arm
      - name: octobox
        image: us.gcr.io/jeefme-185614/octobox:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: RAILS_ENV
          value: development
        - name: OCTOBOX_DATABASE_NAME
          value: postgres
        - name: OCTOBOX_DATABASE_USERNAME
          value: postgres
        - name: OCTOBOX_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: OCTOBOX_DATABASE_HOST
          value: postgresql
        - name: REDIS_URL
          value: redis
        - name: MINIMUM_REFRESH_INTERVAL
          value: "5"
        - name: PERSONAL_ACCESS_TOKENS_ENABLED
          value: "1"
        - name: RAILS_LOG_TO_STDOUT
          value: "yes"
        - name: FETCH_SUBJECT
          value: "true"
        # ocotobox issues with arm
        # bootsnap issue https://github.com/Shopify/bootsnap/issues/67
        # ruby issue https://bugs.ruby-lang.org/issues/13670
        - name: DISABLE_SPRING
          value: "true"
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth
              key: client_id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth
              key: client_secret

---
apiVersion: v1
kind: Service
metadata:
  namespace: octobox
  name: octobox
  labels:
    app: octobox
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: octobox
