apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: octobox
  namespace: octobox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: octobox
        k8s-app: octobox
    spec:
      containers:
      # https://raw.githubusercontent.com/octobox/octobox/master/docker-compose.yml
      # you have to rebuild the container, because arm
      - name: octobox
        image: us.gcr.io/jeefme-185614/octobox:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: RAILS_ENV
          value: development
        - name: OCTOBOX_DATABASE_NAME
          value: postgres
        - name: OCTOBOX_DATABASE_USERNAME
          value: postgres
        - name: OCTOBOX_DATABASE_PASSWORD
          value: somethingeasy
        - name: OCTOBOX_DATABASE_HOST
          value: postgresql.octobox
        - name: REDIS_URL
          value: redis.octobox
        - name: MINIMUM_REFRESH_INTERVAL
          value: "5"
        - name: PERSONAL_ACCESS_TOKENS_ENABLED
          value: "1"
        - name: RAILS_LOG_TO_STDOUT
          value: "yes"
        # ocotobox issues with arm
        # bootsnap issue https://github.com/Shopify/bootsnap/issues/67
        # ruby issue https://bugs.ruby-lang.org/issues/13670
        - name: DISABLE_SPRING
          value: "true"
        # - name: GITHUB_CLIENT_ID
        #   value: ${GITHUB_CLIENT_ID}
        # - name: GITHUB_CLIENT_SECRET
        #   value: ${GITHUB_CLIENT_SECRET}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: octobox
  name: octobox
  namespace: octobox
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    k8s-app: octobox
  type: LoadBalancer
