---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: octobox.jeef.me
  namespace: octobox
  annotations:
    kubernetes.io/ingress.class: traefik
    # traefik.ingress.kubernetes.io/redirect-entry-point: https
    # traefik.ingress.kubernetes.io/redirect-replacement: https://octobox.jeef.me/$1
    # traefik.ingress.kubernetes.io/redirect-regex: ^http://octobox.jeef.me/(.*)
spec:
  rules:
  - host: octobox.jeef.me
    http:
      paths:
      - path: /
        backend:
          serviceName: octobox
          servicePort: 3000
