---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: octobox.jeef.me
  namespace: octobox
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: octobox.jeef.me
    http:
      paths:
      - backend:
          serviceName: octobox
          servicePort: 5000
