---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana.jeef.me
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
    # ingress.kubernetes.io/auth-type: "basic"
    # ingress.kubernetes.io/auth-secret: "dashboard-htaccess"
spec:
  rules:
  - host: grafana.jeef.me
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana
          servicePort: 80
