# https://manpages.debian.org/stretch/bridge-utils/bridge-utils-interfaces.5.en.html
# https://wiki.debian.org/BridgeNetworkConnections
---
- hosts: all
  remote_user: nick
  become: true

  tasks:

  - apt:
      name: bridge-utils
      state: present

  - name: set eth0 to manual
    copy:
      dest: /etc/network/interfaces.d/eth0
      content: |
        allow-hotplug eth0
        iface eth0 inet manual
    when: eth1 in ansible_interfaces

  - name: set eth1 to manual
    copy:
      dest: /etc/network/interfaces.d/eth1
      content: |
        allow-hotplug eth1
        iface eth1 inet manual
    when: eth1 in ansible_interfaces

  - name: set eth2 to manual
    copy:
      dest: /etc/network/interfaces.d/eth2
      content: |
        allow-hotplug eth2
        iface eth2 inet manual
    when: eth2 in ansible_interfaces

  - name: add the bridge device
    copy:
      dest: /etc/network/interfaces.d/br0
      content: |
        iface br0 inet dhcp
          bridge_ports regex eth*
          bridge_stp off
          bridge_waitport 90
          bridge_fd 0
    when: eth1 in ansible_interfaces

  - shell: ifup br0
