---
- hosts: all

  tasks:

  - name: stop docker and kubelet
    systemd:
      name: "{{ item }}"
      state: stopped
      enabled: false
    with_items:
    - docker
    - kubelet

  - name: umount it
    shell: umount /var/lib/docker/overlay2

  - name: remove docker data dir
    file:
      name: /var/lib/docker
      state: absent

  - name: start docker and kubelet
    systemd:
      name: "{{ item }}"
      state: started
      enabled: true
    with_items:
    - docker
    - kubelet
