---
- hosts: all

  tasks:

  - name: install key for the goog repo
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

  - name: install repo from the goog
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present

  - name: update apt cache because you have to do this on debian
    apt:
      update_cache: yes

  - name: install the dang packages
    apt: name={{item}} state=installed
    with_items:
      - kubelet
      - kubeadm
      - kubectl

  - name: no more swap
    command: swapoff -a

  - name: sysctl stuff
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

  - name: more sysctl stuff
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      state: present

  # - name: setup flex volumes ? for rook
  #   copy:
  #     content: |
  #       [Service]
  #       # Environment="KUBELET_EXTRA_ARGS=--volume-plugin-dir=/var/lib/kubelet/volumeplugins"
  #       Environment="KUBE_FEATURE_GATES=PersistentLocalVolumes=true,VolumeScheduling=true,MountPropagation=true"
  #     dest: /etc/systemd/system/kubelet.service.d/09-overrides.conf

  # - name: create cni dir
  #   file:
  #     path: "{{ item }}"
  #     state: directory
  #   with_items:
  #     - /etc/cni
  #     - /etc/cni/net.d

  # - name: flannel config
  #   copy:
  #     content: |
  #       {
  #         "name": "kube-pi-net",
  #         "type": "flannel"
  #       }
  #     dest: /etc/cni/net.d/10-flannel.conf

  # - name: enable the service
  #   service:
  #     name: kubelet
  #     state: started
  #     enabled: true
