---
- hosts: all
  remote_user: nick
  become: true

  tasks:

  - name: install key for the goog repo
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

  - name: install repo from the goog
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present

  - name: install the dang packages
    apt: name={{item}} state=installed
    with_items:
      - kubelet
      - kubeadm
      - kubectl

  - name: enable the service
    service:
      name: kubelet
      state: started
      enabled: true
