---
- hosts: raspi[2345].pi.jeef.me

  tasks:

  - name: run kubeadm
    shell: kubeadm join 192.168.2.40:443 --ignore-preflight-errors=SystemVerification --token 549xgb.1zqdl5my64932khe --discovery-token-ca-cert-hash sha256:c009ea6eaa515ed99e18f93c99785090c9386da1b94be6d3c808d1a5c6f791a2
