---
- hosts: all

  tasks:

  - name: install key for the goog repo
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

  - name: install repo from the goog
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present

  - name: update apt cache because you have to do this on debian
    apt:
      update_cache: yes

  - name: install the dang packages
    apt:
      state: present
      name:
        - kubelet
        - kubeadm
        - kubectl
        - nfs-common # storage backend
        - aufs-dev
        - aufs-tools
        - aufs-dkms

  - name: lock the kube packages to prevent update
    shell: apt-mark hold {{item}}
    with_items:
      - kubelet
      - kubeadm
      - kubectl

  - name: this kernel module is required
    modprobe:
      name: br_netfilter
      state: present

  - name: no more swap
    command: swapoff -a

  - name: sysctl stuff
    sysctl:
      name: vm.swappiness
      value: 0
      state: present
      sysctl_set: yes

  - name: more sysctl stuff
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present
      sysctl_set: yes

  - name: even more sysctl stuff
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      state: present
      sysctl_set: yes
