---
- hosts: raspi[2345].pi.jeef.me

  tasks:

  - name: run kubeadm
    shell: kubeadm join 192.168.2.40:443 --token fwonbq.cjdwe1j8w6sa8i3t --discovery-token-ca-cert-hash sha256:62cda28764e225497275650577bfcedd84ef99d35c62fb00a29dcceaf5ed5b1f
