---
- hosts: raspi2.pi.jeef.me

  tasks:

  - name: install deps
    apt:
      state: present
      name:
        - nfs-kernel-server
        - nfs-common
        - portmap

  - name: mount flash drive as /data
    mount:
      state: mounted
      path: /data
      src: /dev/sda
      fstype: f2fs

  - name: make sure exports dir is created
    file:
      path: /data/{{ item }}
      state: directory
    with_items:
    - postgres
    - influxdb
    - traefik
    - grafana

  - name: export /data/postgres
    lineinfile:
      path: /etc/exports
      regexp: /data/{{ item }}
      line: /data/{{ item }}      *(rw,sync,no_subtree_check,no_root_squash)
    with_items:
    - postgres
    - influxdb
    - traefik
    - grafana

  - name: prevent access to nfs local services
    lineinfile:
      path: /etc/hosts.deny
      regexp: "rpcbind mountd nfsd statd lockd rquotad"
      line: "rpcbind mountd nfsd statd lockd rquotad : ALL"

  - name: allow the rest
    lineinfile:
      path: /etc/hosts.allow
      regexp: "rpcbind mountd nfsd statd lockd rquotad"
      line: "rpcbind mountd nfsd statd lockd rquotad : ALL : allow"

  - shell: exportfs -ra
  - name: restart nfs server
    service:
      name: nfs-kernel-server
      enabled: yes
      state: restarted
