---
- hosts: all

  tasks:

  - name: install key for hypriot
    apt_key:
      url: https://packagecloud.io/Hypriot/rpi/gpgkey

  - apt:
      name: ['vim','git','htop','tree']
      state: present

  - apt:
      update_cache: yes
      upgrade: yes
